version: '2.0'
networks:
    my-network:
        external: true

services:
    app-one:
        container_name: flask_app_one
        stdin_open: true
        tty: true
        networks:
          - my-network
        build: 
            context: .
            dockerfile: Dockerfile.one
        ports:
            - "5001:5000"

    app-two:
        container_name: flask_app_two
        stdin_open: true
        tty: true
        networks:
          - my-network        

        build: 
            context: .
            dockerfile: Dockerfile.two
        ports:
            - "5002:5000"
    nginx:
        image: nginx:latest
        networks:
          - my-network
        volumes:
          - ./conf.d:/etc/nginx/conf.d
        container_name: nginx-container
        restart: on-failure
        ports:
            - "80:80"
    mongo:
      image: mongo
      networks:
          - my-network
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example

    mongo-express:
      image: mongo-express
      container_name: mongo-express
      networks:
          - my-network
      restart: always
      ports:
        - 8081:8081
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: example
        ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/